//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.06 at 05:41:03 PM CET 
//

package svggenerated;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Html }
     * 
     */
    public Html createHtml() {
        return new Html();
    }

    /**
     * Create an instance of {@link Html.Body }
     * 
     */
    public Html.Body createHtmlBody() {
        return new Html.Body();
    }

    /**
     * Create an instance of {@link Html.Body.Svg }
     * 
     */
    public Html.Body.Svg createHtmlBodySvg() {
        return new Html.Body.Svg();
    }

    /**
     * Create an instance of {@link Html.Body.Svg.Circle }
     * 
     */
    public Html.Body.Svg.Circle createHtmlBodySvgCircle() {
        return new Html.Body.Svg.Circle();
    }

}
